### ISSUE TITLE
Difference between addResource and addResourceExtended

### ISSUE THREAD

**Issue by thenoahhein** [Developer-DAO/devie-bot#2]
@AidenMontgomery
Wanted to get discussion going here on which we should be working off of? It looks like you've, well....Extended....The addResource file. Should we just start working off of that one?

I didn't catch this in the merge.

**Comment by AidenMontgomery** [comment]
Ah yeah, I created the 'extended' version because I wasn't sure if the idea was going to work at all and wanted to keep your clean copy around for reference.
I think that we can remove the original 'addResource' file and rename the new 'addResourceExtended'.

**Comment by thenoahhein** [comment]
got it. I'll do that next time I start hacking on it!
